data_file: /home/cbw233/datasets/age/total_img_list.txt # file that include paths of all images with label
data_file_info: /home/cbw233/datasets/age/total_crop_info.json # file that storage all detect info
margin: 0
img_size: 160 # image size to be into model
test_time_mode: tta # [normal, tta] # if use "test time augmentation"
num_classes: 101 # age classes
num_workers: 8
test_size: 0.2
batch_size: 32
cuda: true
lr: 0.0001
epoch: 30
loss: focal # ['normal', 'focal']
early_stop: 5 # -1 to disable
patience: 2 # -1 to disable scheduler
snap_model: # if set, will recover from snap model
train_augmentation: # ['resize', 'center_crop', 'random_flip', 'random_crop', 'random_jit', 'random_rotate']
  resize: 200
  center_crop: 180
  random_flip: 0.5
  random_jit: [[0.5, 2], [0.5, 2], [0.5, 2]]
  random_rotate: [-15, 15]
test_preprocess: # ['resize', 'center_crop', 'random_flip', 'random_crop', 'random_jit', 'random_rotate']
  resize: 200
  center_crop: 180
test_time_augmentation:  # ['resize', 'center_crop', 'random_flip', 'random_crop', 'random_jit', 'random_rotate']
  random_flip: 1.0
  random_jit: [[0.5, 2], [0.5, 2], [0.5, 2]]
  random_rotate: [-15, 15]
stn: false # whether use stn block

